version: '3'

services:
  db_mysql: # MySQL Server
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - 3306:3306
    volumes:
      - db_mysql:/var/lib/mysql

  backend:
    build:
      context: ../backend
      dockerfile: ../infrastructure/Dockerfile.backend
    volumes:
      - ../backend:/app
    ports:
      - 8080:8080


volumes:
  db_mysql: