name: Test Suite

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Docker Containers
        run: |
          cd infrastructure
          docker compose up --build -d

      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd backend
          python3 -m pytest
